### Importing libraries

In [1]:
import numpy as np
import pandas as pd

### Loading and analysing the data

In [2]:
x_y_train = pd.read_csv("twitter_x_y_train.csv")

In [3]:
x_y_train

tweet_id airline_sentiment     airline  \
0      567900433542488064          negative   Southwest   
1      569989168903819264          positive   Southwest   
2      568089179520954368          positive      United   
3      568928195581513728          negative   Southwest   
4      568594180014014464          negative      United   
5      569677636613439488          negative      United   
6      569658903044218880          negative       Delta   
7      568542766860541952          positive       Delta   
8      570116209263427584          negative      United   
9      568870144891600896          positive   Southwest   
10     567793635892174848          negative   Southwest   
11     569879497891303424           neutral       Delta   
12     568517827482685440          positive  US Airways   
13     568212893012860928          negative   Southwest   
14     569270187725160449          negative  US Airways   
15     567816651900583936          negative  US Airways   
16     569690131235340288          negative    American   
17     569932678688055296          negative       Delta   
18     569939494465462272          negative       Delta   
19     569958224968982528          negative    American   
20     568361346464497664          negative  US Airways   
21     568126682336534529           neutral   Southwest   
22     568883826333777920          negative  US Airways   
23     570055700790931456          negative      United   
24     568804026789138433          positive      United   
25     567925054853496832           neutral      United   
26     568434301496381441          negative       Delta   
27     570083397873373184          negative      United   
28     568585356586586113          positive   Southwest   
29     570022265343123456          positive    American   
...                   ...               ...         ...   
10950  569125697530101760          positive       Delta   
10951  569682747712770048          negative   Southwest   
10952  569372333267394560          negative   Southwest   
10953  569333972452265985          negative      United   
10954  568426579874996224          negative   Southwest   
10955  570018254271463424          negative       Delta   
10956  568118177537744897           neutral   Southwest   
10957  568522861205266432          negative  US Airways   
10958  570290993339244547          negative      United   
10959  569624009354170369          negative  US Airways   
10960  568841631585021952          negative      United   
10961  569262534232039427          negative       Delta   
10962  569308255966666753           neutral      United   
10963  569369008580874240          negative  US Airways   
10964  569008708174262272          negative      United   
10965  570164810144481280           neutral      United   
10966  568417151176060929          negative      United   
10967  567617081336950784          negative   Southwest   
10968  569664787946164224          negative    American   
10969  568531020267458561          positive   Southwest   
10970  570283248301043712          negative   Southwest   
10971  569087442092826624           neutral       Delta   
10972  570051488875020288          negative  US Airways   
10973  569676702030262272          negative    American   
10974  569676404893163520          positive   Southwest   
10975  569934458364813313           neutral    American   
10976  568564006329434113          positive      United   
10977  569643648910028801          negative  US Airways   
10978  568864981917110272          negative  US Airways   
10979  568929299350179840          negative      United   

      airline_sentiment_gold             name negativereason_gold  \
0                        NaN    ColeyGirouard                 NaN   
1                        NaN    WalterFaddoul                 NaN   
2                        NaN        LocalKyle                 NaN   
3                        NaN      amccarthy19                 NaN   
4            

In [4]:
x_y_train.columns

Index(['tweet_id', 'airline_sentiment', 'airline', 'airline_sentiment_gold',
       'name', 'negativereason_gold', 'retweet_count', 'text', 'tweet_coord',
       'tweet_created', 'tweet_location', 'user_timezone'],
      dtype='object')

In [5]:
x_y_train.drop(['tweet_id', 'airline', 'airline_sentiment_gold',
       'name', 'negativereason_gold', 'retweet_count', 'tweet_coord',
       'tweet_created', 'tweet_location', 'user_timezone'], axis = 1, inplace = True)

In [6]:
x_y_train

airline_sentiment                                               text
0              negative  @SouthwestAir I am scheduled for the morning, ...
1              positive  @SouthwestAir seeing your workers time in and ...
2              positive  @united Flew ORD to Miami and back and  had gr...
3              negative     @SouthwestAir @dultch97 that's horse radish 😤🐴
4              negative  @united so our flight into ORD was delayed bec...
5              negative  @united Why did you load us in this flying sar...
6              negative  @JetBlue that is a stock response. Delays not ...
7              positive  @JetBlue That'd be nice! Hoping to rack up eno...
8              negative  @united frankly worse customer service ever. P...
9              positive  @SouthwestAir yeah haha. Never been in one. It...
10             negative  @SouthwestAir MCO-&gt;DCA flight almost full o...
11              neutral  @JetBlue what's the easiest way to get a ticke...
12             positive  @USAirways - love the changes in the lounge - ...
13             negative  @SouthwestAir I receive bad customer service a...
14             negative  @USAirways you're killing me sche a flight to ...
15             negative  @USAirways 8 weeks to refund this ticket - 037...
16             negative  @AmericanAir no private msg me and will provid...
17             negative  can you not? RT @JetBlue Our fleet's on fleek....
18             negative  @JetBlue any info on why flight 704 from SJU t...
19             negative  @AmericanAir, I've tried no less than 8 times ...
20             negative  @USAirways new problem...had wrong last name o...
21              neutral  @SouthwestAir Any possible chance of SWA bring...
22             negative  @USAirways @AmericanAir who runs the show at t...
23             negative  @united computers are down but you stopped giv...
24             positive          @united good fly!! #United #businessFirst
25              neutral  @united I am flying from msp to dxb, my child ...
26             negative  @JetBlue loves Cancelled Flightling tickets an...
27             negative  @united In ORD, waited 20 min after crew membe...
28             positive  @SouthwestAir Jason (108639) at Gate #3 in SAN...
29             positive  @AmericanAir everything for sorted out. Thanks...
...                 ...                                                ...
10950          positive  @JetBlue Even though this flight #226 didn't h...
10951          negative  @SouthwestAir very disappointed in your handli...
10952          negative  @SouthwestAir flight Cancelled Flightled out o...
10953          negative  @united when I read it say ' in some cases' ca...
10954          negative  @SouthwestAir you're giving everyone tix for #...
10955          negative  @JetBlue Am I the only one who had to look tha...
10956           neutral                    @SouthwestAir go south everyone
10957          negative  @USAirways 4 hours Late Flightr And i lost my ...
10958          negative  @united I sure did.   I had to drive a total o...
10959          negative  @USAirways his name is Rett Cavan, he has a go...
10960          negative  @united 3 times my flight has been delayed and...
10961          negative  @JetBlue there is no supervisor available, so ...
10962           neutral                                  @united following
10963          negative  @USAirways even alternate options are allready...
10964          negative  @united Also your at-gate monitor showed 23 em...
10965           neutral                             @united Okay thank you
10966          negative  @united - vacation days: relevant, Ritz in PR ...
10967          negative  @SouthwestAir you guys there? Are we on hour 2...
10968          negative  @AmericanAir we are through. I can quit you. I...
10969          positive          @SouthwestAir thank you! ❤️❤️❤️ you guys!
10970          negative  @SouthwestAir went to purchase a flight that I...
10971           neutral  @JetBl

In [7]:
x_y_train.shape

(10980, 2)

In [8]:
 x_y_train["text"][222]

"@united wont transfer flight ticket to accompany an 11 yr old who's active military mom had to have emergency brain surgery? WOW!!"

### Preparing the training and test dataset according to how we need them

In [9]:
y = x_y_train["airline_sentiment"]

In [10]:
y.shape

(10980,)

In [11]:
x_y_train.text[2]

'@united Flew ORD to Miami and back and  had great crew, service on both legs. THANKS'

In [12]:
def Punctuation(string): # removing punctuations in text only before splitting them
  
    # punctuation marks 
    punctuationss = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
  
    # traverse the given string and if any punctuation 
    # marks occur replace it with null 
    for x in string.lower(): 
        if x in punctuationss: 
            string = string.replace(x, "") 
    return string

In [13]:
text_documents = []
for text_doc in x_y_train.text:
    text_documents.append(Punctuation(text_doc).split(" "))

In [14]:
len(text_documents)

10980

In [15]:
text_documents[10979]

['united',
 'you',
 'are',
 'by',
 'far',
 'the',
 'worst',
 'airline',
 '4',
 'plane',
 'delays',
 'on',
 '1',
 'round',
 'trip',
 'flight',
 'How',
 'is',
 'that',
 'possible']

#### Importing NLTK libraries

In [16]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet


####  Collecting all the stop words

In [17]:
from string import punctuation

In [18]:
stops = stopwords.words("english")
stops = stops+ list(punctuation) + [" ",""] # also removing blanks and spaces

In [19]:
stops

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

#### Cleaning the tweets

In [20]:
def get_pos_tag(pos):
    if pos.startswith("J"):
        return wordnet.ADJ
    elif pos.startswith("V"):
        return wordnet.VERB
    elif pos.startswith("N"):
        return wordnet.NOUN
    elif pos.startswith("R"):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [21]:
lemmatizer = WordNetLemmatizer()
def clean_words(words):
    clean_words_list = []
    for w in words:
        if w.lower() not in stops:
            pos = pos_tag([w]) # pass an array in pos_tag always importantttttt
            lemma = lemmatizer.lemmatize(w,pos = get_pos_tag(pos[0][1]))
            clean_words_list.append(lemma.lower())
    return clean_words_list

In [22]:
text_documents[2]

['united',
 'Flew',
 'ORD',
 'to',
 'Miami',
 'and',
 'back',
 'and',
 '',
 'had',
 'great',
 'crew',
 'service',
 'on',
 'both',
 'legs',
 'THANKS']

In [23]:
clean_words(text_documents[7777]) 

['southwestair',
 'fly',
 'delta',
 'week',
 'gogo',
 'good',
 'tweet',
 'sent',
 'didnt',
 'even',
 'send',
 'land',
 'thats',
 'bad']

### Making features using count vectorizer

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [25]:
texts_join = [" ".join(clean_words(text_doc)) for text_doc in text_documents ]


In [26]:
len(texts_join)

10980

In [27]:
texts_join[2]

'united flew ord miami back great crew service leg thanks'

In [28]:
x_train,x_test,y_train,y_test = train_test_split(texts_join,y)

In [29]:
count_vec = CountVectorizer(max_features = 3000,ngram_range = (1,2))

In [30]:
sklearn_x_train = count_vec.fit_transform(x_train)

In [31]:
sklearn_x_test = count_vec.transform(x_test)

In [32]:
print(sklearn_x_train.todense())
print(count_vec.get_feature_names())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['10', '10 day', '10 hour', '10 hr', '10 min', '10 minute', '100', '1000', '10000', '11', '1130', '12', '12 hour', '12 hr', '13', '130', '136', '14', '140', '140 character', '15', '15 hour', '15 hr', '15 min', '15 minute', '150', '16', '17', '18', '1800', '19', '1hr', '1k', '1st', '1st class', '1st time', '20', '20 min', '20 minute', '200', '200 fee', '2015', '21', '219', '22', '222', '224', '23', '24', '24 hour', '24 hr', '24hrs', '25', '25 hour', '25 hr', '25 min', '25 minute', '26', '27', '2day', '2days', '2hrs', '2nd', '2nd time', '2pm', '30', '30 min', '30 minute', '300', '32', '34', '35', '35 min', '39', '3am', '3rd', '3rd time', '40', '40 min', '40 minute', '400', '45', '45 min', '45 minute', '4th', '50', '50 min', '500', '530', '5th', '60', '600', '630', '728', '75', '7am', '80', '800', '800 number', '90', '90 min', 'a320', 'aa', 'abc', 'ability', 'able', 'abl

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

### Using Random Forest

In [81]:
clf1 = RandomForestClassifier()
clf1.fit(sklearn_x_train ,y_train)
clf1.score(sklearn_x_test,y_test)

S:\Apps\anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.7289617486338797

### SVM

In [82]:
clf2 = SVC()
clf2.fit(sklearn_x_train ,y_train)
clf2.score(sklearn_x_test,y_test)

S:\Apps\anaconda\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.6240437158469946

### KNN

In [83]:
clf3 = KNeighborsClassifier()
clf3.fit(sklearn_x_train ,y_train)
clf3.score(sklearn_x_test,y_test)

0.47795992714025504

### Naive_bayes

In [84]:
clf4 = MultinomialNB()
clf4.fit(sklearn_x_train ,y_train)
clf4.score(sklearn_x_test,y_test)

0.7562841530054645

In [54]:
clf5 = LogisticRegression()
clf5.fit(sklearn_x_train ,y_train)
clf5.score(sklearn_x_test,y_test)

0.775591985428051

## Getting the test data ready

In [35]:
x_test_pd = pd.read_csv("twitter_x_test.csv")

In [36]:
x_test_pd

tweet_id         airline airline_sentiment_gold  \
0     569682010270101504        American                    NaN   
1     569608307184242688        American                    NaN   
2     567879304593408001       Southwest                    NaN   
3     569757651539660801      US Airways                    NaN   
4     569900705852608513        American                    NaN   
5     569235062862036992          United                    NaN   
6     569824422279950336      US Airways                    NaN   
7     567880416201293824      US Airways                    NaN   
8     570021943899877377      US Airways                    NaN   
9     569690664029462529        American                    NaN   
10    570271205300703232          United                    NaN   
11    569996446348517376      US Airways                    NaN   
12    568105481018822656       Southwest                    NaN   
13    570275010759102466        American                    NaN   
14    568085308727808000       Southwest                    NaN   
15    569981015378112512      US Airways                    NaN   
16    570271064141352960          United                    NaN   
17    567852264099999744           Delta                    NaN   
18    567848374113693697          United                    NaN   
19    569678787383857152           Delta                    NaN   
20    569522923029041153       Southwest                    NaN   
21    569552374882299904          United                    NaN   
22    569917183385432064        American                    NaN   
23    569677660890116096        American                    NaN   
24    569567629083430912      US Airways                    NaN   
25    568761693997674496           Delta                    NaN   
26    570114451120074752        American                    NaN   
27    569870442388983808      US Airways                    NaN   
28    569968023592943616           Delta                    NaN   
29    568262481698803712          United                    NaN   
...                  ...             ...                    ...   
3630  570177698166923267      US Airways                    NaN   
3631  568182386409607168       Southwest                    NaN   
3632  567763748559937536       Southwest                    NaN   
3633  568752061682208768           Delta                    NaN   
3634  568436613384155136           Delta                    NaN   
3635  568870841120731138      US Airways                    NaN   
3636  569369390178799616      US Airways                    NaN   
3637  568188595456118785       Southwest                    NaN   
3638  570031379456643072          United                    NaN   
3639  570275970046775297        American                    NaN   
3640  569696080121569280        American                    NaN   
3641  567735337246806016      US Airways                    NaN   
3642  570299642887442433       Southwest                    NaN   
3643  568265016253628416      US Airways                    NaN   
3644  569134299024367616          United                    NaN   
3645  568134973728755712       Southwest                    NaN   
3646  569437674257276930      US Airways                    NaN   
3647  569903058299199488        American                    NaN   
3648  569618309357940737           Delta                    NaN   
3649  568830757730422784          United                    NaN   
3650  569667602148151296       Southwest                    NaN   
3651  568527605063757824      US Airways                    NaN   
3652  569503983623999488           Delta                    NaN   
3653  567896040982069249      US Airways                    NaN   
3654  569960303514923009        American                    NaN   
3655  570304244001193984      US Airways                    NaN   
3656  567847737061941249      US Airways                    NaN   
3657  567823564167192576  Virgin America                    NaN

In [37]:
x_test_pd.drop(['tweet_id', 'airline', 'airline_sentiment_gold',
       'name', 'negativereason_gold', 'retweet_count', 'tweet_coord',
       'tweet_created', 'tweet_location', 'user_timezone'], axis = 1, inplace = True)

In [38]:
x_test_pd

text
0     @AmericanAir In car gng to DFW. Pulled over 1h...
1     @AmericanAir after all, the plane didn’t land ...
2     @SouthwestAir can't believe how many paying cu...
3     @USAirways I can legitimately say that I would...
4     @AmericanAir still no response from AA. great ...
5     @united we have developers flying down tmrw mo...
6                     @USAirways hello??? Anyone there?
7     @USAirways @husainhaqqani Mr. Husain u shld pr...
8     @USAirways not likely, flightaware says plane ...
9     @AmericanAir they don't even give an option to...
10    @united your announcement for pre boarding onl...
11    @USAirways it is really embarrassing when aski...
12    @SouthwestAir I will not have my passport in t...
13    @AmericanAir this delayed bag was for my frien...
14    @SouthwestAir Didn't see travel had to be comp...
15    @USAirways awesome... Doors close in 2 minutes...
16    @united I flew United last month and the exper...
17    @JetBlue Accepting #Apple Pay - Mobile Enterpr...
18    @united $55 cab ride to dfw from love got me m...
19    @JetBlue ill call in the morning. too upset ri...
20    @SouthwestAir @AARP #tfw1 Appreciate the tweet...
21    @united what's the status of flight 1008 Bogot...
22    @AmericanAir literally just stopped allowing p...
23    @AmericanAir I really want to get home. Tonigh...
24    @USAirways I've been on hold at the reservatio...
25    @JetBlue Denver-Boston 2/10 flight 994  and Bo...
26    @AmericanAir nothing to do with Mother Nature,...
27    @USAirways you would rather a while plane get ...
28    @JetBlue hi guys, do you have a general enquir...
29    @united we finally just arrive to Bogota, good...
...                                                 ...
3630                         @USAirways nope not yet...
3631  @SouthwestAir So far so good! http://t.co/16c9...
3632  @SouthwestAir @CBSsoxfan you get to hold? call...
3633  @JetBlue Really!? That's good to hear! Thanks ...
3634  @JetBlue trying to charge us $550 dollars cash...
3635  @USAirways can u tell me if 5238 from clt to J...
3636  @USAirways Your customer service is  non-exist...
3637  @SouthwestAir Whoa. Thanks and that's what I w...
3638  @United THANK U! Secured room for the night Th...
3639  @AmericanAir I'm not sure what happened to my ...
3640  @AmericanAir pretty bad at #DFW no updates two...
3641  @USAirways Just contaced EYEWITNESS NEWS about...
3642  @SouthwestAir thx. Make it right. Help Meagan ...
3643  @USAirways I didn't Cancelled Flight my flight...
3644  @united your "Airserv" contractors aren't wort...
3645  @SouthwestAir @taylormdowns We share that valu...
3646  @USAirways on hold now over 2 hrs on one phone...
3647  @AmericanAir the flight I'm trying to change i...
3648  @JetBlue the fact that #ChrisHasMadeUsBLUSH is...
3649           @united Did somebody say flight upgrade?
3650      @SouthwestAir how do I get my companion pass?
3651  @USAirways tells me to talk to @AmericanAir ab...
3652          @JetBlue you want me to talk to the wall?
3653  @USAirways Now, the JFK Baggage Office has act...
3654  @AmericanAir Least you could do would be to re...
3655  @USAirways Been stuck for 40+ minutes due to l...
3656  @USAirways 4 hours... 4 hours... FOUR HOURS.  ...
3657  Nice RT @VirginAmerica: The man of steel might...
3658  @AmericanAir Aww Thanks AA..DFW was on GMA up ...
3659  @united the lounge tells us they have no pillo...

[3660 rows x 1 columns]

In [39]:
text_documents_test = []
for text_doc in x_test_pd.text:
    text_documents_test.append(Punctuation(text_doc).split(" "))

In [40]:
text_documents_test[2]

['SouthwestAir',
 'cant',
 'believe',
 'how',
 'many',
 'paying',
 'customers',
 'you',
 'left',
 'high',
 'and',
 'dry',
 'with',
 'no',
 'reason',
 'for',
 'flight',
 'Cancelled',
 'Flightlations',
 'Monday',
 'out',
 'of',
 'BDL',
 'Wow']

In [41]:
len(text_documents_test)

3660

In [42]:
texts_join_test = [" ".join(clean_words(text_doc)) for text_doc in text_documents_test ]


In [43]:
sklearn_x_test_final = count_vec.transform(texts_join_test)

In [44]:
sklearn_x_test_final.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### Predicting the values

### Using random forest

In [103]:
y_pred_rfc = clf1.predict(sklearn_x_test_final)

In [111]:
len(y_pred_rfc)

3660

In [115]:
np.savetxt("twitter_pred_rfc",y_pred_rfc,delimiter = ",",fmt = "%s")

### Using Naive_bayes

In [104]:
y_pred_NB = clf4.predict(sklearn_x_test_final)

In [114]:
np.savetxt("twitter_pred_NB",y_pred_NB,delimiter = ",",fmt = "%s")

### Logistic Regression

In [45]:
y_pred_LR = clf5.predict(sklearn_x_test_final)

In [46]:
np.savetxt("twitter_pred_LR",y_pred_LR,delimiter = ",",fmt = "%s")